package model;
// Generated 7 oct. 2013 18:10:30 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Document generated by hbm2java
 */
public class Document  implements java.io.Serializable {


     private Integer idDoc;
     private String nom;
     private String adressePhysique;
     private String extension;
     private int taille;
     private Set<TableDroit> tableDroits = new HashSet<TableDroit>(0);
     private Set<Metadonnee> metadonnees = new HashSet<Metadonnee>(0);
     private Set<Signataire> signataires = new HashSet<Signataire>(0);

    public Document() {
    }

	
    public Document(String nom, String adressePhysique, String extension, int taille) {
        this.nom = nom;
        this.adressePhysique = adressePhysique;
        this.extension = extension;
        this.taille = taille;
    }
    public Document(String nom, String adressePhysique, String extension, int taille, Set<TableDroit> tableDroits, Set<Metadonnee> metadonnees, Set<Signataire> signataires) {
       this.nom = nom;
       this.adressePhysique = adressePhysique;
       this.extension = extension;
       this.taille = taille;
       this.tableDroits = tableDroits;
       this.metadonnees = metadonnees;
       this.signataires = signataires;
    }
   
    public Integer getIdDoc() {
        return this.idDoc;
    }
    
    public void setIdDoc(Integer idDoc) {
        this.idDoc = idDoc;
    }
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }
    public String getAdressePhysique() {
        return this.adressePhysique;
    }
    
    public void setAdressePhysique(String adressePhysique) {
        this.adressePhysique = adressePhysique;
    }
    public String getExtension() {
        return this.extension;
    }
    
    public void setExtension(String extension) {
        this.extension = extension;
    }
    public int getTaille() {
        return this.taille;
    }
    
    public void setTaille(int taille) {
        this.taille = taille;
    }
    public Set<TableDroit> getTableDroits() {
        return this.tableDroits;
    }
    
    public void setTableDroits(Set<TableDroit> tableDroits) {
        this.tableDroits = tableDroits;
    }
    public Set<Metadonnee> getMetadonnees() {
        return this.metadonnees;
    }
    
    public void setMetadonnees(Set<Metadonnee> metadonnees) {
        this.metadonnees = metadonnees;
    }
    public Set<Signataire> getSignataires() {
        return this.signataires;
    }
    
    public void setSignataires(Set<Signataire> signataires) {
        this.signataires = signataires;
    }




}


