package model;
// Generated 7 oct. 2013 13:38:41 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Droit generated by hbm2java
 */
public class Droit  implements java.io.Serializable {


     private Integer idDroit;
     private String nom;
     private Set tableDroits = new HashSet(0);

    public Droit() {
    }

	
    public Droit(String nom) {
        this.nom = nom;
    }
    public Droit(String nom, Set tableDroits) {
       this.nom = nom;
       this.tableDroits = tableDroits;
    }
   
    public Integer getIdDroit() {
        return this.idDroit;
    }
    
    public void setIdDroit(Integer idDroit) {
        this.idDroit = idDroit;
    }
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }
    public Set getTableDroits() {
        return this.tableDroits;
    }
    
    public void setTableDroits(Set tableDroits) {
        this.tableDroits = tableDroits;
    }




}


