package model;
// Generated 2 oct. 2013 17:01:31 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Droit generated by hbm2java
 */
public class Droit  implements java.io.Serializable {


     private Integer idDroit;
     private String nom;
     private Set documents = new HashSet(0);

    public Droit() {
    }

	
    public Droit(String nom) {
        this.nom = nom;
    }
    public Droit(String nom, Set documents) {
       this.nom = nom;
       this.documents = documents;
    }
   
    public Integer getIdDroit() {
        return this.idDroit;
    }
    
    public void setIdDroit(Integer idDroit) {
        this.idDroit = idDroit;
    }
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }
    public Set getDocuments() {
        return this.documents;
    }
    
    public void setDocuments(Set documents) {
        this.documents = documents;
    }




}


