package model;
// Generated 7 oct. 2013 18:10:30 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Metadonnee generated by hbm2java
 */
public class Metadonnee  implements java.io.Serializable {


     private int idDoc;
     private String version;
     private Document document;
     private Utilisateur utilisateur;
     private String etatdudoc;
     private String titredocument;
     private Date dateinsertion;
     private Date datevalider;
     private Date datedesignataire;

    public Metadonnee() {
    }

	
    public Metadonnee(int idDoc, Document document, Utilisateur utilisateur, String etatdudoc, String titredocument, Date dateinsertion) {
        this.idDoc = idDoc;
        this.document = document;
        this.utilisateur = utilisateur;
        this.etatdudoc = etatdudoc;
        this.titredocument = titredocument;
        this.dateinsertion = dateinsertion;
    }
    public Metadonnee(int idDoc, Document document, Utilisateur utilisateur, String etatdudoc, String titredocument, Date dateinsertion, Date datevalider, Date datedesignataire) {
       this.idDoc = idDoc;
       this.document = document;
       this.utilisateur = utilisateur;
       this.etatdudoc = etatdudoc;
       this.titredocument = titredocument;
       this.dateinsertion = dateinsertion;
       this.datevalider = datevalider;
       this.datedesignataire = datedesignataire;
    }
   
    public int getIdDoc() {
        return this.idDoc;
    }
    
    public void setIdDoc(int idDoc) {
        this.idDoc = idDoc;
    }
    public String getVersion() {
        return this.version;
    }
    
    public void setVersion(String version) {
        this.version = version;
    }
    public Document getDocument() {
        return this.document;
    }
    
    public void setDocument(Document document) {
        this.document = document;
    }
    public Utilisateur getUtilisateur() {
        return this.utilisateur;
    }
    
    public void setUtilisateur(Utilisateur utilisateur) {
        this.utilisateur = utilisateur;
    }
    public String getEtatdudoc() {
        return this.etatdudoc;
    }
    
    public void setEtatdudoc(String etatdudoc) {
        this.etatdudoc = etatdudoc;
    }
    public String getTitredocument() {
        return this.titredocument;
    }
    
    public void setTitredocument(String titredocument) {
        this.titredocument = titredocument;
    }
    public Date getDateinsertion() {
        return this.dateinsertion;
    }
    
    public void setDateinsertion(Date dateinsertion) {
        this.dateinsertion = dateinsertion;
    }
    public Date getDatevalider() {
        return this.datevalider;
    }
    
    public void setDatevalider(Date datevalider) {
        this.datevalider = datevalider;
    }
    public Date getDatedesignataire() {
        return this.datedesignataire;
    }
    
    public void setDatedesignataire(Date datedesignataire) {
        this.datedesignataire = datedesignataire;
    }




}


