package model;
// Generated 7 oct. 2013 18:10:30 by Hibernate Tools 3.2.1.GA



/**
 * Signataire generated by hbm2java
 */
public class Signataire  implements java.io.Serializable {


     private SignataireId id;
     private Document document;
     private Utilisateur utilisateur;
     private int validation;

    public Signataire() {
    }

    public Signataire(SignataireId id, Document document, Utilisateur utilisateur, int validation) {
       this.id = id;
       this.document = document;
       this.utilisateur = utilisateur;
       this.validation = validation;
    }
   
    public SignataireId getId() {
        return this.id;
    }
    
    public void setId(SignataireId id) {
        this.id = id;
    }
    public Document getDocument() {
        return this.document;
    }
    
    public void setDocument(Document document) {
        this.document = document;
    }
    public Utilisateur getUtilisateur() {
        return this.utilisateur;
    }
    
    public void setUtilisateur(Utilisateur utilisateur) {
        this.utilisateur = utilisateur;
    }
    public int getValidation() {
        return this.validation;
    }
    
    public void setValidation(int validation) {
        this.validation = validation;
    }




}


