package model;
// Generated 7 oct. 2013 13:38:41 by Hibernate Tools 3.2.1.GA



/**
 * TableDroit generated by hbm2java
 */
public class TableDroit  implements java.io.Serializable {


     private Integer idTabledroit;
     private Droit droit;
     private Document document;

    public TableDroit() {
    }

    public TableDroit(Droit droit, Document document) {
       this.droit = droit;
       this.document = document;
    }
   
    public Integer getIdTabledroit() {
        return this.idTabledroit;
    }
    
    public void setIdTabledroit(Integer idTabledroit) {
        this.idTabledroit = idTabledroit;
    }
    public Droit getDroit() {
        return this.droit;
    }
    
    public void setDroit(Droit droit) {
        this.droit = droit;
    }
    public Document getDocument() {
        return this.document;
    }
    
    public void setDocument(Document document) {
        this.document = document;
    }




}


