package model;
// Generated 2 oct. 2013 17:01:31 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Utilisateur generated by hbm2java
 */
public class Utilisateur  implements java.io.Serializable {


     private String login;
     private String password;
     private int idDroit;
     private String nom;
     private String prenom;
     private String service;
     private Set signataires = new HashSet(0);

    public Utilisateur() {
    }

	
    public Utilisateur(String login, String password, int idDroit, String nom, String prenom, String service) {
        this.login = login;
        this.password = password;
        this.idDroit = idDroit;
        this.nom = nom;
        this.prenom = prenom;
        this.service = service;
    }
    public Utilisateur(String login, String password, int idDroit, String nom, String prenom, String service, Set signataires) {
       this.login = login;
       this.password = password;
       this.idDroit = idDroit;
       this.nom = nom;
       this.prenom = prenom;
       this.service = service;
       this.signataires = signataires;
    }
   
    public String getLogin() {
        return this.login;
    }
    
    public void setLogin(String login) {
        this.login = login;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public int getIdDroit() {
        return this.idDroit;
    }
    
    public void setIdDroit(int idDroit) {
        this.idDroit = idDroit;
    }
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }
    public String getPrenom() {
        return this.prenom;
    }
    
    public void setPrenom(String prenom) {
        this.prenom = prenom;
    }
    public String getService() {
        return this.service;
    }
    
    public void setService(String service) {
        this.service = service;
    }
    public Set getSignataires() {
        return this.signataires;
    }
    
    public void setSignataires(Set signataires) {
        this.signataires = signataires;
    }




}


